### ISSUE TITLE
AndroZoo Dataset

### ISSUE THREAD

**Issue by E0HYL** [HarrialX/GraphBackdoor#1]
Hi, thanks for the contribution. 
Will the AndroZoo dataset (and maybe the feature generation script) be released?

**Comment by zhaohan-xi** [comment]
Hi, the AndroZoo dataset is provided by our collaborators, thus we will not release it due to confidentiality. But you can refer to the following process to construct your own Android malware call graphs:
- first, you can collect raw APK files from [AndroZoo](https://androzoo.uni.lu) website.
- then, you can use [Soot](https://github.com/noidsirius/SootTutorial) to transfer APK files to graph format. (The recommended URL may not be the most useful one, you can simply search for any other tutorials that parse APK files by Soot). [This paper](https://www.ndss-symposium.org/wp-content/uploads/2017/09/ndss2017_03B-3_Mariconti_paper.pdf) may also be helpful in call graph construction.
- once you have a set of call graphs, you can construct node features by original static features or other custom ways.

**Comment by E0HYL** [comment]
Thanks for the kind reply.
